name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install conan
      run: pip install conan
    - name: Install deps, configure
      run: |
        mkdir build
        cd build
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
        export CXX=/usr/bin/g++-9
        export CMAKE_CXX_COMPILER=/usr/bin/g++-9
        conan install .. -s compiler=gcc -s compiler.version=9 --build=missing
    - name: build
      run: |
        cd build
        cmake -S .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/g++-9
        make
    - name: run tests
      run: |
        cd build
        make test
    - name: doc
      run: |
        cd build
        make doc
    - name: Deploy doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/html
