name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install conan
      run: pip install conan
    - name: Install deps, configure, build and run tests
      run: |
        mkdir build
        cd build
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan install ..
        cmake -S .. -DCMAKE_BUILD_TYPE=Debug
        make
        make test
